import { initializeApp } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";
import { getFirestore, collection, getDocs, doc, setDoc } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";
import { firebaseConfig, seedGifts } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=id=>document.getElementById(id);
$("loginForm").onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("email").value,$("password").value)}catch{$("loginMsg").textContent="E-mail ou senha inválidos.";$ ("loginMsg").style.display="block"}};
$("logout").onclick=()=>signOut(auth);
onAuthStateChanged(auth,user=>{$("loginForm").classList.toggle("hidden",!!user);$("panel").classList.toggle("hidden",!user);if(user)loadAdmin();});
async function loadAdmin(){const snap=await getDocs(collection(db,"gifts"));let gifts=snap.docs.map(d=>({id:d.id,...d.data()}));if(!gifts.length)gifts=seedGifts;const reserved=gifts.filter(g=>g.reserved),visible=gifts.filter(g=>g.visible!==false);$("adminStats").innerHTML=`<div><b>${gifts.length}</b><span>cadastrados</span></div><div><b>${visible.length}</b><span>visíveis</span></div><div><b>${reserved.length}</b><span>reservados</span></div>`;renderManage(gifts);}
function renderManage(gifts){const categories=["Todos",...new Set(gifts.map(g=>g.category))];$("categoryAdmin").innerHTML=categories.map(c=>`<option>${c}</option>`).join("");renderItems(gifts);$("categoryAdmin").onchange=()=>filterItems(gifts);$("adminSearch").oninput=()=>filterItems(gifts);}
function filterItems(gifts){const q=$("adminSearch").value.toLowerCase().trim(),cat=$("categoryAdmin").value;renderItems(gifts.filter(g=>(cat==="Todos"||g.category===cat)&&(`${g.name} ${g.category}`.toLowerCase().includes(q))));}
function renderItems(gifts){$("manageList").innerHTML=gifts.map(g=>`<div class="manage-item"><span class="manage-emoji">${g.emoji}</span><div class="manage-info"><b>${g.name}</b><small>${g.category}${g.reserved?` · 🔴 reservado por ${escapeHtml(g.reservedBy||"")}`:""}</small></div><label class="switch"><input type="checkbox" data-id="${g.id}" ${g.visible!==false?"checked":""}><span></span><em>${g.visible!==false?"Visível":"Oculto"}</em></label></div>`).join("");document.querySelectorAll(".switch input").forEach(input=>input.onchange=()=>toggleVisibility(input));}
async function toggleVisibility(input){const id=input.dataset.id,visible=input.checked;input.disabled=true;try{await setDoc(doc(db,"gifts",id),{visible},{merge:true});await loadAdmin();}catch{input.checked=!visible;alert("Não foi possível alterar a visibilidade. Verifique o Firebase.");}finally{input.disabled=false;}}
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));}
$("seed").onclick=async()=>{if(!confirm("Cadastrar/sincronizar os 100 presentes? Reservas e configurações de visibilidade existentes serão preservadas."))return;for(const g of seedGifts)await setDoc(doc(db,"gifts",g.id),{name:g.name,category:g.category,emoji:g.emoji,description:g.description},{merge:true});await loadAdmin();alert("100 presentes estão cadastrados. Agora você pode escolher quais ficam visíveis para os convidados.");};
