// Configuração do seu Web App no Firebase (Casa Nova)
export const firebaseConfig = {
  apiKey: "AIzaSyCGHqBz9OX-pGDbvQ22Msn1GEmrz5dNmqA",
  authDomain: "casa-nova-ad182.firebaseapp.com",
  projectId: "casa-nova-ad182",
  storageBucket: "casa-nova-ad182.firebasestorage.app",
  messagingSenderId: "963100479641",
  appId: "1:963100479641:web:827e320821e1371c85e808",
  measurementId: "G-DP74K9D4Z9"
};

// Lista completa com 100 sugestões. "visible" controla se o item aparece para os convidados.
const items = [
["Jogo de panelas","Cozinha","🍳","Um conjunto de panelas para nossa nova cozinha."],
["Jogo de talheres","Cozinha","🍴","Talheres para as refeições do dia a dia."],
["Liquidificador","Cozinha","🥤","Para preparar sucos, vitaminas e receitas."],
["Air fryer","Cozinha","🍟","Para facilitar nossas receitas e lanches."],
["Batedeira","Cozinha","🧁","Para nossas receitas e sobremesas."],
["Sanduicheira","Cozinha","🥪","Para lanches rápidos."],
["Cafeteira","Cozinha","☕","Para começar os dias com café."],
["Chaleira elétrica","Cozinha","🫖","Para chá, café e água quente."],
["Torradeira","Cozinha","🍞","Para nossos cafés da manhã."],
["Jogo de copos","Cozinha","🥛","Copos para a nova casa."],
["Jogo de taças","Cozinha","🍷","Para receber amigos e comemorar."],
["Jogo de pratos","Cozinha","🍽️","Pratos para as refeições."],
["Assadeiras","Cozinha","🥘","Para nossas receitas no forno."],
["Travessas","Cozinha","🥣","Para servir refeições e receber visitas."],
["Potes herméticos","Cozinha","🫙","Para organizar alimentos."],
["Kit de utensílios de cozinha","Cozinha","🥄","Espátulas, conchas e outros utensílios."],
["Escorredor de louça","Cozinha","🧼","Para deixar a pia organizada."],
["Lixeira de cozinha","Cozinha","🗑️","Uma lixeira para a cozinha."],
["Tábua de corte","Cozinha","🔪","Para preparar alimentos."],
["Jogo de facas","Cozinha","🔪","Facas para o preparo das refeições."],
["Jogo de potes de vidro","Cozinha","🫙","Para guardar e organizar alimentos."],
["Organizador de temperos","Cozinha","🧂","Para manter os temperos organizados."],
["Porta-temperos","Cozinha","🌿","Para deixar a cozinha prática e bonita."],
["Balança de cozinha","Cozinha","⚖️","Para medir ingredientes com precisão."],
["Jarra de água","Cozinha","💧","Para servir água e sucos."],
["Garrafa térmica","Cozinha","🫖","Para manter bebidas quentes."],
["Marmitas","Cozinha","🍱","Para organizar refeições e levar comida."],
["Porta-pão","Cozinha","🥖","Para conservar pães e deixar a bancada organizada."],
["Escorredor de macarrão","Cozinha","🍝","Para massas e outros alimentos."],
["Forma de bolo","Cozinha","🍰","Para nossas receitas doces."],
["Forma de pizza","Cozinha","🍕","Para noites de pizza em família."],
["Panela de pressão","Cozinha","🥘","Para agilizar o preparo das refeições."],
["Frigideira antiaderente","Cozinha","🍳","Para preparos rápidos do dia a dia."],
["Jogo de cama casal","Quarto","🛏️","Para deixar nosso quarto mais confortável."],
["Jogo de toalhas","Banheiro","🛁","Toalhas para nossa nova casa."],
["Edredom casal","Quarto","🛌","Para noites mais aconchegantes."],
["Cobertor casal","Quarto","🧣","Para os dias frios."],
["Travesseiros","Quarto","😴","Conforto para nossas noites."],
["Protetor de colchão","Quarto","🛏️","Para proteger o colchão."],
["Cortina para quarto","Quarto","🪟","Para completar o quarto."],
["Tapete para quarto","Quarto","🧶","Para deixar o quarto mais aconchegante."],
["Organizador de guarda-roupa","Quarto","👕","Para manter nossas roupas organizadas."],
["Kit de cabides","Quarto","👔","Para organizar o guarda-roupa."],
["Colcha casal","Quarto","🛏️","Para decorar e proteger a cama."],
["Manta decorativa","Quarto","🧶","Para deixar o quarto aconchegante."],
["Almofadas","Quarto","🛋️","Para trazer conforto e decoração."],
["Protetor de travesseiro","Quarto","🛏️","Para conservar os travesseiros."],
["Cesto para roupas","Quarto","🧺","Para organizar as roupas usadas."],
["Sapateira","Quarto","👟","Para manter os calçados organizados."],
["Jogo de banheiro","Banheiro","🚿","Para organizar e decorar o banheiro."],
["Espelho para banheiro","Banheiro","🪞","Um espelho para o banheiro."],
["Porta-toalhas","Banheiro","🧴","Para manter as toalhas organizadas."],
["Organizador de banheiro","Banheiro","🧺","Para organizar produtos de higiene."],
["Porta-sabonete","Banheiro","🧼","Para deixar a pia organizada."],
["Porta-escovas","Banheiro","🪥","Para organizar a bancada."],
["Tapete antiderrapante","Banheiro","🛁","Para mais conforto e segurança."],
["Cesto de lixo para banheiro","Banheiro","🗑️","Para manter o banheiro organizado."],
["Dispenser de sabonete","Banheiro","🧴","Para deixar a pia prática e bonita."],
["Kit de toalhas de rosto","Banheiro","🧖","Toalhas para o dia a dia."],
["Roupão de banho","Banheiro","🥼","Para momentos de conforto."],
["Nécessaire organizadora","Banheiro","🧴","Para guardar produtos de higiene."],
["Cortina para sala","Sala","🪟","Para deixar a sala mais aconchegante."],
["Tapete para sala","Sala","🧶","Para decorar e deixar a sala confortável."],
["Ventilador","Sala","🌀","Para deixar a casa mais fresca."],
["Abajur","Quarto","💡","Para criar uma iluminação aconchegante."],
["Luminária","Sala","💡","Para iluminar e decorar."],
["Relógio de parede","Sala","🕐","Para decorar nossa casa."],
["Almofadas para sofá","Sala","🛋️","Para deixar o sofá mais confortável."],
["Manta para sofá","Sala","🧣","Para criar um ambiente aconchegante."],
["Quadro decorativo","Sala","🖼️","Para dar personalidade à nossa casa."],
["Espelho decorativo","Sala","🪞","Para ampliar e decorar o ambiente."],
["Porta-retratos","Sala","🖼️","Para guardar momentos especiais da família."],
["Vaso decorativo","Sala","🪴","Para trazer um toque especial ao ambiente."],
["Planta para decoração","Sala","🌿","Para deixar a casa mais viva."],
["Aspirador de pó","Limpeza","🧹","Para facilitar a limpeza da casa."],
["Vassoura","Limpeza","🧹","Para a limpeza do dia a dia."],
["Rodo","Limpeza","🧽","Para limpar os pisos."],
["Kit de limpeza","Limpeza","🧴","Produtos e acessórios para a casa."],
["Pá de lixo","Limpeza","🧹","Para facilitar a limpeza dos pisos."],
["Balde","Limpeza","🪣","Para limpeza e tarefas domésticas."],
["Mop","Limpeza","🧽","Para uma limpeza prática dos pisos."],
["Flanela e panos de limpeza","Limpeza","🧼","Para manter a casa limpa e organizada."],
["Escova para limpeza","Limpeza","🧹","Para limpar diferentes superfícies."],
["Organizador de produtos de limpeza","Limpeza","🧴","Para guardar os produtos com segurança."],
["Varal de chão","Lavanderia","👕","Para secar nossas roupas."],
["Ferro de passar","Lavanderia","👔","Para cuidar das roupas."],
["Tábua de passar","Lavanderia","🧺","Para acompanhar o ferro de passar."],
["Cesto organizador de lavanderia","Lavanderia","🧺","Para organizar produtos e roupas."],
["Prendedores de roupa","Lavanderia","📎","Para facilitar a secagem das roupas."],
["Organizador para lavanderia","Lavanderia","🧴","Para manter a área de serviço organizada."],
["Cabideiro de chão","Lavanderia","👚","Para deixar roupas e acessórios organizados."],
["Kit de sacos para roupas delicadas","Lavanderia","👕","Para proteger roupas na lavagem."],
["Kit de ferramentas","Casa","🛠️","Para pequenos reparos em casa."],
["Escada doméstica","Casa","🪜","Para alcançar lugares altos com segurança."],
["Extensão elétrica","Casa","🔌","Para ampliar as opções de tomadas."],
["Filtro de linha","Casa","🔌","Para organizar e proteger aparelhos eletrônicos."],
["Caixa organizadora","Casa","📦","Para guardar objetos e manter tudo organizado."],
["Organizador multiuso","Casa","🗂️","Para aproveitar melhor os espaços da casa."],
["Kit de pilhas","Casa","🔋","Para controles, relógios e pequenos aparelhos."],
["Lanterna","Casa","🔦","Para ter iluminação de emergência."],
];

export const seedGifts = items.map((x, i) => ({
  id: `item-${String(i + 1).padStart(3, "0")}`,
  name: x[0], category: x[1], emoji: x[2], description: x[3],
  reserved: false, reservedBy: "", visible: true
}));
