export const seedGifts = [
  {
    "id": "gift-001",
    "name": "Jogo de panelas",
    "category": "Cozinha",
    "emoji": "🍳",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-002",
    "name": "Jogo de talheres",
    "category": "Cozinha",
    "emoji": "🍴",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-003",
    "name": "Liquidificador",
    "category": "Cozinha",
    "emoji": "🥤",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-004",
    "name": "Air fryer",
    "category": "Cozinha",
    "emoji": "🍟",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-005",
    "name": "Batedeira",
    "category": "Cozinha",
    "emoji": "🧁",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-006",
    "name": "Sanduicheira",
    "category": "Cozinha",
    "emoji": "🥪",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-007",
    "name": "Cafeteira",
    "category": "Cozinha",
    "emoji": "☕",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-008",
    "name": "Chaleira elétrica",
    "category": "Cozinha",
    "emoji": "🫖",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-009",
    "name": "Torradeira",
    "category": "Cozinha",
    "emoji": "🍞",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-010",
    "name": "Jogo de copos",
    "category": "Cozinha",
    "emoji": "🥛",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-011",
    "name": "Jogo de taças",
    "category": "Cozinha",
    "emoji": "🍷",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-012",
    "name": "Jogo de pratos",
    "category": "Cozinha",
    "emoji": "🍽️",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-013",
    "name": "Assadeiras",
    "category": "Cozinha",
    "emoji": "🥘",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-014",
    "name": "Travessas",
    "category": "Cozinha",
    "emoji": "🥣",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-015",
    "name": "Potes herméticos",
    "category": "Cozinha",
    "emoji": "🫙",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-016",
    "name": "Kit de utensílios de cozinha",
    "category": "Cozinha",
    "emoji": "🥄",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-017",
    "name": "Escorredor de louça",
    "category": "Cozinha",
    "emoji": "🧼",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-018",
    "name": "Lixeira de cozinha",
    "category": "Cozinha",
    "emoji": "🗑️",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-019",
    "name": "Tábua de corte",
    "category": "Cozinha",
    "emoji": "🔪",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-020",
    "name": "Jogo de facas",
    "category": "Cozinha",
    "emoji": "🔪",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-021",
    "name": "Potes de vidro",
    "category": "Cozinha",
    "emoji": "🫙",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-022",
    "name": "Organizador de temperos",
    "category": "Cozinha",
    "emoji": "🧂",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-023",
    "name": "Porta-temperos",
    "category": "Cozinha",
    "emoji": "🌿",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-024",
    "name": "Balança de cozinha",
    "category": "Cozinha",
    "emoji": "⚖️",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-025",
    "name": "Jarra de água",
    "category": "Cozinha",
    "emoji": "💧",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-026",
    "name": "Garrafa térmica",
    "category": "Cozinha",
    "emoji": "🫖",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-027",
    "name": "Kit de marmitas",
    "category": "Cozinha",
    "emoji": "🍱",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-028",
    "name": "Porta-pão",
    "category": "Cozinha",
    "emoji": "🥖",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-029",
    "name": "Escorredor de macarrão",
    "category": "Cozinha",
    "emoji": "🍝",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-030",
    "name": "Forma de bolo",
    "category": "Cozinha",
    "emoji": "🍰",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-031",
    "name": "Forma de pizza",
    "category": "Cozinha",
    "emoji": "🍕",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-032",
    "name": "Panela de pressão",
    "category": "Cozinha",
    "emoji": "🥘",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-033",
    "name": "Frigideira antiaderente",
    "category": "Cozinha",
    "emoji": "🍳",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-034",
    "name": "Wok",
    "category": "Cozinha",
    "emoji": "🥘",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-035",
    "name": "Cuscuzeira",
    "category": "Cozinha",
    "emoji": "🍲",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-036",
    "name": "Leiteira",
    "category": "Cozinha",
    "emoji": "🥛",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-037",
    "name": "Kit de medidores",
    "category": "Cozinha",
    "emoji": "🥄",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-038",
    "name": "Ralador multiuso",
    "category": "Cozinha",
    "emoji": "🧀",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-039",
    "name": "Peneira",
    "category": "Cozinha",
    "emoji": "🥣",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-040",
    "name": "Abridor de latas",
    "category": "Cozinha",
    "emoji": "🥫",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-041",
    "name": "Saca-rolhas",
    "category": "Cozinha",
    "emoji": "🍷",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-042",
    "name": "Porta-guardanapos",
    "category": "Cozinha",
    "emoji": "🧻",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-043",
    "name": "Jogo americano",
    "category": "Cozinha",
    "emoji": "🍽️",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-044",
    "name": "Sousplat",
    "category": "Cozinha",
    "emoji": "🍽️",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-045",
    "name": "Pano de prato",
    "category": "Cozinha",
    "emoji": "🧺",
    "description": "Um item para deixar nossa cozinha mais prática e gostosa de usar.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-046",
    "name": "Jogo de cama casal",
    "category": "Quarto",
    "emoji": "🛏️",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-047",
    "name": "Edredom casal",
    "category": "Quarto",
    "emoji": "🛌",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-048",
    "name": "Cobertor casal",
    "category": "Quarto",
    "emoji": "🧣",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-049",
    "name": "Travesseiros",
    "category": "Quarto",
    "emoji": "😴",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-050",
    "name": "Protetor de colchão",
    "category": "Quarto",
    "emoji": "🛏️",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-051",
    "name": "Cortina para quarto",
    "category": "Quarto",
    "emoji": "🪟",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-052",
    "name": "Tapete para quarto",
    "category": "Quarto",
    "emoji": "🧶",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-053",
    "name": "Organizador de guarda-roupa",
    "category": "Quarto",
    "emoji": "👕",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-054",
    "name": "Kit de cabides",
    "category": "Quarto",
    "emoji": "👔",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-055",
    "name": "Colcha casal",
    "category": "Quarto",
    "emoji": "🛏️",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-056",
    "name": "Manta decorativa",
    "category": "Quarto",
    "emoji": "🧶",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-057",
    "name": "Almofadas",
    "category": "Quarto",
    "emoji": "🛋️",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-058",
    "name": "Protetor de travesseiro",
    "category": "Quarto",
    "emoji": "🛏️",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-059",
    "name": "Cesto para roupas",
    "category": "Quarto",
    "emoji": "🧺",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-060",
    "name": "Sapateira",
    "category": "Quarto",
    "emoji": "👟",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-061",
    "name": "Jogo de fronhas",
    "category": "Quarto",
    "emoji": "🛏️",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-062",
    "name": "Saia para cama",
    "category": "Quarto",
    "emoji": "🛏️",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-063",
    "name": "Organizador de gavetas",
    "category": "Quarto",
    "emoji": "🗄️",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-064",
    "name": "Cabideiro",
    "category": "Quarto",
    "emoji": "👚",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-065",
    "name": "Mesa de cabeceira",
    "category": "Quarto",
    "emoji": "🛏️",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-066",
    "name": "Luminária de cabeceira",
    "category": "Quarto",
    "emoji": "💡",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-067",
    "name": "Abajur",
    "category": "Quarto",
    "emoji": "💡",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-068",
    "name": "Espelho de corpo inteiro",
    "category": "Quarto",
    "emoji": "🪞",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-069",
    "name": "Manta para cama",
    "category": "Quarto",
    "emoji": "🧶",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-070",
    "name": "Caixa organizadora para armário",
    "category": "Quarto",
    "emoji": "📦",
    "description": "Um item para deixar nosso quarto mais confortável e aconchegante.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-071",
    "name": "Jogo de banheiro",
    "category": "Banheiro",
    "emoji": "🚿",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-072",
    "name": "Espelho para banheiro",
    "category": "Banheiro",
    "emoji": "🪞",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-073",
    "name": "Porta-toalhas",
    "category": "Banheiro",
    "emoji": "🧴",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-074",
    "name": "Organizador de banheiro",
    "category": "Banheiro",
    "emoji": "🧺",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-075",
    "name": "Porta-sabonete",
    "category": "Banheiro",
    "emoji": "🧼",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-076",
    "name": "Porta-escovas",
    "category": "Banheiro",
    "emoji": "🪥",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-077",
    "name": "Tapete antiderrapante",
    "category": "Banheiro",
    "emoji": "🛁",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-078",
    "name": "Cesto de lixo para banheiro",
    "category": "Banheiro",
    "emoji": "🗑️",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-079",
    "name": "Dispenser de sabonete",
    "category": "Banheiro",
    "emoji": "🧴",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-080",
    "name": "Kit de toalhas de rosto",
    "category": "Banheiro",
    "emoji": "🧖",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-081",
    "name": "Roupão de banho",
    "category": "Banheiro",
    "emoji": "🥼",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-082",
    "name": "Nécessaire organizadora",
    "category": "Banheiro",
    "emoji": "🧴",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-083",
    "name": "Jogo de toalhas de banho",
    "category": "Banheiro",
    "emoji": "🛁",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-084",
    "name": "Porta-papel higiênico",
    "category": "Banheiro",
    "emoji": "🧻",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-085",
    "name": "Escova sanitária",
    "category": "Banheiro",
    "emoji": "🧹",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-086",
    "name": "Suporte para shampoo",
    "category": "Banheiro",
    "emoji": "🧴",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-087",
    "name": "Organizador de cosméticos",
    "category": "Banheiro",
    "emoji": "💄",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-088",
    "name": "Cesto de roupa suja",
    "category": "Banheiro",
    "emoji": "🧺",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-089",
    "name": "Tapete de banheiro",
    "category": "Banheiro",
    "emoji": "🛁",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-090",
    "name": "Cortina de box",
    "category": "Banheiro",
    "emoji": "🚿",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-091",
    "name": "Gancho de parede",
    "category": "Banheiro",
    "emoji": "🪝",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-092",
    "name": "Kit de potes para banheiro",
    "category": "Banheiro",
    "emoji": "🫙",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-093",
    "name": "Bandeja para banheiro",
    "category": "Banheiro",
    "emoji": "🧴",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-094",
    "name": "Prateleira de banheiro",
    "category": "Banheiro",
    "emoji": "🧱",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-095",
    "name": "Kit de toalhas de mão",
    "category": "Banheiro",
    "emoji": "🧖",
    "description": "Um item para organizar e deixar o banheiro mais funcional.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-096",
    "name": "Cortina para sala",
    "category": "Sala",
    "emoji": "🪟",
    "description": "Um item para deixar a sala mais confortável e com a nossa cara.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-097",
    "name": "Tapete para sala",
    "category": "Sala",
    "emoji": "🧶",
    "description": "Um item para deixar a sala mais confortável e com a nossa cara.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-098",
    "name": "Ventilador",
    "category": "Sala",
    "emoji": "🌀",
    "description": "Um item para deixar a sala mais confortável e com a nossa cara.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-099",
    "name": "Luminária de piso",
    "category": "Sala",
    "emoji": "💡",
    "description": "Um item para deixar a sala mais confortável e com a nossa cara.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  },
  {
    "id": "gift-100",
    "name": "Relógio de parede",
    "category": "Sala",
    "emoji": "🕐",
    "description": "Um item para deixar a sala mais confortável e com a nossa cara.",
    "reserved": false,
    "reservedBy": "",
    "reservedAt": "",
    "visible": true
  }
];
